add aws/errorcode.json
bsc-s2/resource pull request #2
Opened 2018-03-29 06:17 UTC by godgitgold

使用 s2/src/errorcode.csv 转换为 errorcode.json 
尽量不影响s2/src/s2offline.py 文件，
文件校验决定在pykit中写完解析文件模块，测试时会检查.json和.csv 是否一致

2018-03-30 02:12 UTC, drmingdrmer commented on aws/errorcode.json
> +        "httpcode": "403 Forbidden",
403 和后面的描述为啥不分开? 出于什么考虑

2018-03-31 06:30 UTC, drmingdrmer requested changes

2018-03-31 06:30 UTC, drmingdrmer commented on aws/errorcode.json
> +        "httpcode": "403",
code用数字不用字符串

2018-03-31 06:30 UTC, drmingdrmer commented on aws/errorcode.json
>          "httpcode": "N/A",
不要留N/A的. 给分配一个错误码. 如何选择跟树龙商量下可以.

2018-03-31 06:34 UTC, godgitgold commented on aws/errorcode.json
> +        "httpcode": "403",
知道了

2018-03-31 06:34 UTC, godgitgold commented on aws/errorcode.json
>          "httpcode": "N/A",
好的，知道了

2018-04-02 08:03 UTC, godgitgold commented on aws/errorcode.json
>          "httpcode": "N/A",
原因：1. s2/src/s2offline.py 中将'N/A'转换为400
           2. pykit/aws/errorcode.yaml 中 相应错误的 httpcode 为 400
结果：将httpcode = 'N/A' 置换为 httpcode = 400
           status = 'N/A' 置换为 status = 'Bad Request'

2018-04-11 08:26 UTC, drmingdrmer approved these changes

2018-04-11 10:53 UTC, lishulong approved these changes

2018-04-12 04:55 UTC, merged